"""Initial schema for projects and tasks

Revision ID: 330f2a8f8579
Revises: 7c9c74e3516a
Create Date: 2025-11-14 00:06:14.580851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '330f2a8f8579'
down_revision: Union[str, Sequence[str], None] = '7c9c74e3516a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
